config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  github_authenticate(org: ENV['GITHUB_ORG']) do
    resources :services do
      resources :metrics, shallow: true
    end
  end
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  DATAPOINT_SOURCE_VALUES = %w(graphite cloudwatch)
  CLOUDWATCH_NAMESPACES = %w(AWS/EC2 AWS/RDS AWS/SNS AWS/SQS)

  belongs_to :service

  validates :title, presence: true
  validates :datapoint_source, inclusion: { in: DATAPOINT_SOURCE_VALUES }
  validates :datapoint_name, presence: true
  validates :alarm_warning, presence: true
  validates :alarm_error, presence: true

  validates :cloudwatch_namespace, inclusion: { in: CLOUDWATCH_NAMESPACES }, if: :cloudwatch_metric?
  validates :cloudwatch_identifier, presence: true, if: :cloudwatch_metric?

  def cloudwatch_metric?
    datapoint_source == 'cloudwatch'
  end

  def graphite_metric?
    datapoint_source == 'graphite'
  end

  def datapoints(start_time = nil, end_time = nil)
    return @datapoints unless @datapoints.nil?
    if cloudwatch_metric?
      datapoint_lib = CloudwatchMetric.new(cloudwatch_namespace, datapoint_name, cloudwatch_identifier)
    else
      datapoint_lib = GraphiteMetric.new(title, datapoint_name)
    end
    datapoint_lib.start_time = start_time if start_time
    datapoint_lib.end_time = end_time if end_time
    @datapoints = datapoint_lib.datapoints
  end

  def alarm_state
    return 'error' if alarm_error?
    return 'warning' if alarm_warning?
    'normal'
  end

  def sidebar_data
    attrs = [:summary, :alarm_warning, :alarm_error, :negative_alarming?, :mitigation_steps, :contact]
    attrs.concat([:cloudwatch_namespace, :cloudwatch_identifier]) if cloudwatch_metric?
    attrs.reduce({}) do |hsh, attr|
      hsh[attr] = send(attr)
      hsh
    end
  end

  private
    def latest_datapoint
      return datapoints.map { |point| point unless point.first.nil? }.compact.last.first if graphite_metric?
      datapoints.last.first
    end

    def alarm_error?
      return latest_datapoint < alarm_error if negative_alarming?
      latest_datapoint > alarm_error
    end

    def alarm_warning?
      return false if alarm_error?
      return latest_datapoint < alarm_warning if negative_alarming?
      latest_datapoint > alarm_warning
    end
end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true

  has_many :metrics, dependent: :destroy

  def last_n_metrics(n)
    metrics.order(updated_at: :desc).limit(n)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return redirect_to services_path if github_authenticated?
    @org_name = ENV['GITHUB_ORG'].try(:capitalize)
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric, only: [:show, :edit, :update, :destroy]
  before_action :set_service, only: [:index, :new, :create]

  def index
    @metrics = @service.metrics
  end

  def show
    start_time ||= time_object(params[:start_time])
    end_time ||= time_object(params[:end_time])

    respond_to do |format|
      format.html
      format.json { render json: {
          datapoints: @metric.datapoints(start_time, end_time),
          alarm: {
            error: @metric.alarm_error,
            state: @metric.alarm_state,
            warning: @metric.alarm_warning
          }
        }
      }
    end
  end

  def new
    @metric = @service.metrics.new
  end

  def edit
  end

  def create
    @metric = @service.metrics.new(metric_params)

    if @metric.save
      redirect_to @metric, notice: 'Metric was successfully created.'
    else
      render :new
    end
  end

  def update
    if @metric.update(metric_params)
      redirect_to @metric, notice: 'Metric was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    service = @metric.service
    @metric.destroy
    redirect_to service, notice: 'Metric was successfully destroyed.'
  end

  private
    def set_metric
      @metric = Metric.find(params[:id])
    end

    def set_service
      @service = Service.find(params[:service_id])
    end

    # Only allow a trusted parameter "white list" through.
    def metric_params
      params.require(:metric).permit(:title, :datapoint_source, :datapoint_name, :summary, :mitigation_steps, :contact,
                                     :cloudwatch_namespace, :cloudwatch_identifier, :alarm_warning, :alarm_error,
                                     :negative_alarming)
    end

    def time_object(timestamp)
      Time.at(timestamp.to_i) if timestamp
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BS_ALERT_MAP = {
    "notice" => "warning",
    "alert" => "danger"
  }

  def metric_chart(metric_title, metric_id, opts={})
    content_tag(
      :div,
      nil,
      id: "metric-chart-#{metric_id}",
      class: 'metric-chart',
      data: { title: metric_title, metric_id: metric_id, size: (opts[:size] || :small),  }
    )
  end

  def i(n, title: nil)
    return "" unless n
    content_tag(:i, nil, class: "fa fa-#{n}", title: title)
  end

  def flash_alert(type, msg)
    class_name = BS_ALERT_MAP[type] || type
    content_tag(:div, class: "alert alert-#{class_name}") do
      content_tag(:span, msg) +
      button_tag("&times;".html_safe, data: { dismiss: "alert" }, class: "close").html_safe
    end
  end

  def all_flash_alerts
    content_tag(:div) do
      flash.collect { |type, msg| concat(flash_alert(type, msg)) }
    end
  end
end

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Pulse</h1>
    <p>
      Pulse is a dashboard that uses data from external metric services to render graphs displaying the health of your application.
    </p>
    <p>
      <%= link_to services_path, class: "btn btn-lg btn-default" do %>
        <%= i("github-square") %> Login with GitHub
      <% end %>
      <% if @org_name %>
        <br>
        <small class="text-muted">* You must be a member of the '<%= @org_name %>' organisation.</small>
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pulse</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag 'c3' %>
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css">
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.js"></script>
  <%= javascript_include_tag 'c3' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pulse", github_authenticated? ? services_path : root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
    </div>
  </div>
</div>

<% if @no_container %>
  <%= all_flash_alerts %>
  <%= yield %>
<% else %>
  <div class="container">
    <%= all_flash_alerts %>
    <%= yield %>
  </div>
<% end %>

</body>
</html>

app/views/metrics/_form.html.erb
<%= form_for([@service, @metric]) do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :datapoint_source %><br>
    <%= f.select :datapoint_source, options_for_select(Metric::DATAPOINT_SOURCE_VALUES,  @metric.datapoint_source), {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :datapoint_name %><br>
    <%= f.text_field :datapoint_name, class: 'form-control' %>
  </div>
  <div id="cloudwatch-form-options"<% unless @metric.cloudwatch_metric? %> class="hidden"<% end %>>
    <div class="form-group">
      <%= f.label :cloudwatch_namespace %><br>
      <%= f.select :cloudwatch_namespace, options_for_select(Metric::CLOUDWATCH_NAMESPACES, @metric.cloudwatch_namespace), {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :cloudwatch_identifier %><br>
      <%= f.text_field :cloudwatch_identifier, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :alarm_warning %><br>
    <%= f.text_field :alarm_warning, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :alarm_error %><br>
    <%= f.text_field :alarm_error, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :negative_alarming %><br>
    <%= f.check_box :negative_alarming %>
  </div>
  <div class="form-group">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mitigation_steps %><br>
    <%= f.text_area :mitigation_steps, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact %><br>
    <%= f.text_field :contact, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/metrics/edit.html.erb
<h1>Editing metric</h1>

<%= render 'form' %>

app/views/metrics/index.html.erb
<h1>Listing metrics</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Datapoint source</th>
      <th>Summary</th>
      <th>Mitigation steps</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= metric.title %></td>
        <td><%= metric.datapoint_source %></td>
        <td><%= metric.summary %></td>
        <td><%= metric.mitigation_steps %></td>
        <td><%= metric.contact %></td>
        <td><%= link_to 'Show', metric_path(metric) %></td>
        <td><%= link_to 'Edit', edit_metric_path(metric) %></td>
        <td><%= link_to 'Destroy', metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metric', new_service_metric_path %>

app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= render 'form' %>

app/views/metrics/show.html.erb
<div class="page-header">
  <h1 title="Metric: <%= @metric.title %>">
    <%= i('bar-chart-o') %>
    <%= @metric.title %>
    <small>
      Source: <%= @metric.datapoint_source.capitalize %>
    </small>
  </h1>
</div>
<form action="<% metric_path @metric %>" method="get">
    <div class="row" style="padding-bottom: 15px">
      <div class="col-md-12"><label for="date_range">Time Period: </label></div>
      <div class="col-md-5"><input type="text" class="form-control daterange" data-start_time="<%= params[:start_time] %>" data-end_time="<%= params[:end_time] %>"/></div>
      <div class="col-md-1"><input type="submit" value="Go" class="btn btn-primary" /> </div>
      <input type="hidden" name="start_time" value="<%= params[:start_time] %>" />
      <input type="hidden" name="end_time" value="<%= params[:end_time] %>" />
    </div>
</form>

<div class="row">
  <div class="col-md-3">
    <div class="list-group metric-sidebar">
      <%= link_to services_path, class: "list-group-item", title: "All Services" do %>
        <h5 class="list-group-item-heading">
          <%= i("chevron-left") %> <%= i("cube") %> <%= @metric.service.title %>
        </h5>
      <% end %>

      <div class="list-group-item metric-attr-datapoint_name">
        <h5 class="list-group-item-heading">Datapoint Name</h5>
        <%= content_tag(:pre, @metric.datapoint_name.split(".").join(".\n"), class: "list-group-item-text") %>
      </div>

      <% @metric.sidebar_data.each do |name, value| %>
        <div class="list-group-item metric-attr-<%= name %>">
          <h5 class="list-group-item-heading">
            <%= name.to_s.titleize %>:
          </h5>
          <p class="list-group-item-text">
            <%= value %>
          </p>
        </div>
      <% end %>

      <div class="list-group-item">
        <div class="btn-group">
          <%= link_to edit_metric_path(@metric), class: "btn btn-info" do %>
            <%= i('edit') %> Edit
          <% end %>
          <%= link_to @metric, method: :delete, class: "btn btn-danger",
                      data: { confirm: "Are you sure you want to delete the metric '#{@metric.title}' and it's metrics?" } do %>
            <%= i('trash-o') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-9 panel panel-default">
    <%= metric_chart(@metric.title, @metric.id, size: :big) %>
  </div>
</div>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/services/_service_panel.html.erb
<% metrics = service.last_n_metrics(metric_count) %>
<div class="panel panel-default service-panel">
  <div class="panel-heading">
    <div class="pull-left">
      <%= link_to service do %>
        <h2 class="panel-title">
          <%= i("cube") %> <%= service.title %>
        </h2>
      <% end %>
    </div>
    <div class="btn-group pull-right">
      <% if metrics.any? %>
        <%= link_to new_service_metric_path(service), class: "btn btn-primary", title: "Add Metric" do %>
          <%= i("plus") %> <%= i("bar-chart-o") %>
        <% end %>
      <% end %>
      <%= link_to edit_service_path(service), class: "btn btn-info" do %>
        <%= i('edit') %> Edit
      <% end %>
      <%= link_to service, method: :delete, class: "btn btn-danger",
                  data: { confirm: "Are you sure you want to delete the service '#{service.title}' and it's metrics?" } do %>
        <%= i('trash-o') %>
      <% end %>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="panel-body">
    <div class="row">
      <% metrics.each do |metric| %>
        <%= link_to metric do %>
          <div class="col-md-4">
            <%= metric_chart(metric.title, metric.id) %>
          </div>
        <% end %>
      <% end %>
      <% if metrics.empty? %>
        <div class="text-center">
          You haven't added any metrics yet!
          <%= link_to new_service_metric_path(service), class: "btn btn-primary btn-xs" do %>
            <%= i('bar-chart-o') %> Add Metric
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="panel-footer">
    <small><%= service.description.truncate(200) %></small>
  </div>
</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

app/views/services/index.html.erb
<!-- <div class="row services-title">
  <div class="col-md-6">
    <h1><%= i('cubes') %> Services</h1>
  </div
  <div class="col-md-6">

  </div>
</div> -->

<table class="table table-condensed table-striped">
  <thead>
      <th class="col-sm-1">Service <%= link_to new_service_path do %>
            <%= i('plus') %>
        <% end %></th>
      <th class="col-sm-2">&nbsp;</th>
      <th class="col-sm-2">&nbsp;</th>
      <th class="col-sm-2">&nbsp;</th>
      <th class="col-sm-2">&nbsp;</th>
  </thead>
  <tbody>
  <% @services.each do |service| %>
    <% desired_metrics = 4 %>
    <% metrics = service.last_n_metrics(desired_metrics) %>
    <% metrics_count = metrics.count %>
    <tr>
      <td>
        <%= link_to service do %>
            <h5><%= service.title %></h5>
        <% end %>
      </td>
      <% metrics.each do |metric| %>
      <td>
        <%= link_to metric, class: "no-hover-underline" do %>
          <%= metric_chart(metric.title, metric.id) %>
        <% end %>
      </td>
      <% end %>
      <% if metrics_count < desired_metrics %>
      <% (desired_metrics - metrics.count).times do %>
          <td class="col-center-text">No Graph</td>
      <% end %>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

app/views/services/show.html.erb
<p>
  <%= link_to services_path, class: "btn btn-default", title: "All Services" do %>
    <%= i("chevron-left") %> <%= i("cubes") %>
  <% end %>
</p>

<%= render "service_panel", service: @service, metric_count: nil %>